/**
 * @file
 * @brief ConstantUtil_INPUTヘッダーファイル
 */
#pragma once


#include "ConstantUtil.h"


namespace tml {
namespace ConstantUtil {
namespace INPUT {
	enum class RESOURCE_TYPE : UINT {
		NONE = 0U,
		COUNT
	};
	const UINT RESOURCE_TYPE_COUNT = static_cast<UINT>(tml::ConstantUtil::INPUT::RESOURCE_TYPE::COUNT);
	enum class EVENT_TYPE : UINT {
		NONE = 0U,
		MOUSE,
		KEYBOARD,
		COUNT
	};
	const UINT EVENT_TYPE_COUNT = static_cast<UINT>(tml::ConstantUtil::INPUT::EVENT_TYPE::COUNT);
	enum class MOUSE_EVENT_DATA_TYPE : UINT {
		NONE = 0U,
		LEFT_BUTTON_DOWN = RI_MOUSE_LEFT_BUTTON_DOWN,
		LEFT_BUTTON_UP = RI_MOUSE_RIGHT_BUTTON_DOWN,
		RIGHT_BUTTON_DOWN = RI_MOUSE_RIGHT_BUTTON_DOWN,
		RIGHT_BUTTON_UP = RI_MOUSE_RIGHT_BUTTON_UP,
		MIDDLE_BUTTON_DOWN = RI_MOUSE_MIDDLE_BUTTON_DOWN,
		MIDDLE_BUTTON_UP = RI_MOUSE_MIDDLE_BUTTON_UP,
		SIDE1_BUTTON_DOWN = RI_MOUSE_BUTTON_4_DOWN,
		SIDE1_BUTTON_UP = RI_MOUSE_BUTTON_4_UP,
		SIDE2_BUTTON_DOWN = RI_MOUSE_BUTTON_5_DOWN,
		SIDE2_BUTTON_UP = RI_MOUSE_BUTTON_5_UP,
		DISPLACEMENT = 0x00010000U,
		WHEEL = 0x00020000U
	};
}
}
}


TML_ENUM_CLASS_FLAG_OPERATOR(tml::ConstantUtil::INPUT::MOUSE_EVENT_DATA_TYPE, UINT)
